### ISSUE TITLE
P2P

### ISSUE THREAD

**Issue by AbdelrhmanAmin** [vichuge/PositioningAndFloatingElements#1]
Index.html 36-50: The main element should be a container for the entire sections and remove class= "header" instead, create a new section or div, and add class="header" to it.
Style.css: 164: instead use display: flex.
Style.css 170: instead of having small-border-up & small-border-down, Just delete them and add to .general-content hr{ margin: 15px auto; }
Style.css 51: It's more elegant if you change the padding to that .nav-btn{ padding: 6px 8px 6px 8px;}
Style.css: Add .social-icons1 {    display: flex;
    align-items: center; }
.content-date1 {
align-items: baseline}

**Comment by marilirulita** [comment]
the margins could be responsible design

**Comment by VanessaAoki** [comment]
Hello guys! You have a wonderful project here, but I do like to add some advice beforehand:

1) In order to pass the linter you guys should add the < meta name="viewport" content="width=device-width, initial-scale=1.0" > tag on the head;
2) The TSE guys told us that everything in the navbar should be clickable (with < a > tags, making it cursor: pointer won't do it), so you guys should make all icons, logo image clickable;
3) TSE also recommended that all buttons should have a type, not only classes;
4) Line 70, instead of using the < div > tag, you can (can, meaning it's not mandatory, but it's usually preferable) use the < article > tag, to contain the whole main content;
5) There are 2 fixed bars in this project, the bottom and the top one, keep that in mind;
6) In the bottom section, the recommended articles, our TSE asked us to make both images and article title clickable.

Keep up the great work guys!
